---
title: "MetaQuote Analystic"
output:
  html_document:
    fig_caption: yes
    highlight: null
    keep_md: yes
    theme: null
---

<style>
.main-container {
  width: 960px;
  max-width:1600px;
}
body, td {
  font-size: 10px;
}
</style>

***
## Overview
```{r infos, echo=F}
# attach(REPORT)
copy(INFOS) %>%
  extract(
    j = TIME := time.numeric.to.posixct(TIME)
  ) %>%
  as.data.frame %>%
  htmlTable(rnames = F,
            css.table = "width: 100%; margin-top: 1em; margin-bottom: 1em;",
            css.cell = rep('width: 150px;', 8),
            col.rgroup = c("none", "#F9FAF0"),
            col.columns = c("none", "#F1F0FA"))
```

```{r timeseries, echo=F, fig.align='center', fig.width=13, message=FALSE, warning=FALSE}
TIMESERIE.ACCOUNT %>%
  extract(j = .(TIME, EQUITY, MARGIN.FREE, MARGIN.USED)) %>%
  melt('TIME') %>% {
    ggplot(.) +
      geom_line(aes(x = TIME, y = value, color = variable)) +
      facet_grid(variable ~ ., scales = 'free_y') +
      xlab('EQUITY & MARGIN') +
      ylab(NULL) +
      theme(legend.position = 'none', axis.ticks.x = element_blank()) +
      scale_y_continuous(labels = scales::dollar)
  }
```

```{r period, echo=F}
with(PERIOD, {
  data.table(
    START = int_start(NATURE.INTERVAL),
    NATURAL.PERIOD = as.character(NATURE.PERIOD),
    TRADE.DAYS = TRADE.DAYS,
    END = int_end(NATURE.INTERVAL))
  }) %>%
  htmlTable(rnames = F,
            caption = 'TRADE PERIOD',
            css.table = "width: 100%; margin-top: 1em; margin-bottom: 1em;",
            css.cell = rep('width: 300px;', 4),
            col.rgroup = c("none", "#F9FAF0"),
            col.columns = c("none", "#F1F0FA"))
```

```{r profit & volume, echo=F, fig.align='center', fig.width=13, message=FALSE, warning=FALSE}
lables <- c(BALANCE.DELTA = 'PROFIT', NET.VOLUME = 'VOLUME')
melt(SYMBOLS.PROFIT_VOLUME, c('TIME', 'SYMBOL')) %>% {
  ggplot(.) +
  geom_line(aes(x = TIME, y = value, color = SYMBOL)) +
  facet_grid(variable ~ ., scales = 'free_y', labeller = labeller(variable = lables)) +
  xlab('PROFIT & VOLUME') +
  ylab(NULL) +
  theme(legend.position = 'bottom', legend.direction = 'horizontal', legend.key.size = unit(10, 'pt'),
        legend.title = element_blank())
}
```
  
## Calendar
```{r yield & mddp calendar, echo=F}
yield.calendar(TIMESERIE.ACCOUNT) %>%
  htmlTable(rnames = F,
            caption = 'YIELD CALENDAR',
            css.table = "width: 100%; margin-top: 1em; margin-bottom: 1em;",
            css.cell = rep('width: 85px;', 14),
            col.rgroup = c("none", "#F9FAF0"),
            col.columns = c("none", "#F1F0FA"))
mddp.calendar(TIMESERIE.ACCOUNT) %>%
  htmlTable(rnames = F,
            caption = 'MAX-DRAWDOWN CALENDAR (to EQUITY)',
            css.table = "width: 100%; margin-top: 1em; margin-bottom: 1em;",
            css.cell = rep('width: 85px;', 14),
            col.rgroup = c("none", "#F9FAF0"),
            col.columns = c("none", "#F1F0FA"))
balance.mddp.calendar(TICKETS.EDITED, TICKETS.MONEY) %>%
  htmlTable(rnames = F,
            caption = 'MAX-DRAWDOWN CALENDAR (to BALANCE)',
            css.table = "width: 100%; margin-top: 1em; margin-bottom: 1em;",
            css.cell = rep('width: 85px;', 14),
            col.rgroup = c("none", "#F9FAF0"),
            col.columns = c("none", "#F1F0FA"))
```
  
## Evalution
```{r evaluation, echo=F}
net.profit <- STATISTIC.ACCOUNT.PL[PL == 'TOTAL', SUM]
con.monthly.loss <-
  TIMESERIE.ACCOUNT %>%
  setkey(TIME) %>%
  extract(
    j = .(TIME, BALANCE.DELTA = c(0, BALANCE.DELTA) %>% diff, YM = format(TIME, '%Y%m'))
  ) %>%
  extract(
    j = .(M.PROFIT = sum(BALANCE.DELTA)),
    by = YM
  ) %>%
  extract(j = M.PROFIT) %>% cal.continuous %>% {
    if (length(.$DN.TO)) {
      (.$DN.TO - .$DN.FROM + 1) %>% max
    } else {
      0
    }
  }
trades.per.day <- STATISTIC.ACCOUNT.OTHERS[ITEM == 'TRADE', DAILY]
mdd.portfolio <- STATISTIC.ACCOUNT.OTHERS[MDD == 'MDDP', MDD.VALUE]
win.percent <-
  STATISTIC.ACCOUNT.PL[, SUM] %>% {
  (.)[1] / (.)[3] * 100
  } %>% round(2)
threshold <- c(0, 2, 1, 30, 50)
result.char <- c('FAIL', 'OK')
data.table(
  THEME = c('Net Profit',
            'Monthly Yield',
            'Trades per Day',
            'Max Drawdown Percent',
            'Win Percent'),
  DESCRIPTION = c(sprintf(' greater than %.2f $', threshold[1]),
                  sprintf(' no more than %i Loss in a row', threshold[2]),
                  sprintf(' greater than %.2f trades per day', threshold[3]),
                  sprintf(' less than %.2f %%', threshold[4]),
                  sprintf(' greater than %.2f %%', threshold[5])),
  RESULT = c(sprintf('%.2f $', net.profit),
             sprintf('max %i', con.monthly.loss),
             sprintf('%.2f', trades.per.day),
             sprintf('%.2f %%', mdd.portfolio),
             sprintf('%.2f %%', win.percent)),
  EVALUATION = result.char[c(net.profit > threshold[1],
                             con.monthly.loss <= threshold[2],
                             trades.per.day > threshold[3],
                             mdd.portfolio < threshold[4],
                             win.percent > threshold[5]) + 1]
) %>%
  htmlTable(rnames = F,
            css.table = "width: 100%; margin-top: 1em; margin-bottom: 1em;",
            css.cell = rep('width: 300px;', 4),
            col.rgroup = c("none", "#F9FAF0"),
            col.columns = c("none", "#F1F0FA"))
```
  
## Scores
```{r scores, echo=F}
yearly.yield <- STATISTIC.ACCOUNT.OTHERS[ITEM == 'YIELD', YEARLY]
yield.score <- score.yearly.return(yearly.yield)
mddp <- STATISTIC.ACCOUNT.OTHERS[MDD == 'MDDP', MDD.VALUE]
mddp.score <- score.mddp(mddp)
score <- mean(c(yield.score, mddp.score)) %>% round(0)
data.table(
  YEARLY.YIELD = sprintf('%s     >>>', yearly.yield),
  YIELD.SCORE = sprintf('(%s)     >>>', yield.score %>% round(0)),
  SCORE.LEVEL = sprintf('%s (%s)', level(score), score),
  MDDP.SCORE = sprintf('<<<     (%s)', mddp.score %>% round(0)),
  MDDP.YIELD = sprintf('<<<     %s', mddp)
) %>%
  htmlTable(rnames = F,
            css.table = "width: 100%; margin-top: 1em; margin-bottom: 1em;",
            css.cell = rep('width: 192px;', 5),
            cgroup = c('YEARLY.RETURN', 'LEVEL', 'MAX.DRAWDOWN'),
            n.cgroup = c(2, 1, 2),
            col.rgroup = c("none", "#F9FAF0"),
            col.columns = c(rep("none", 2),
                            "#F1F0FA",
                            rep("none", 2))
            )
```
  
## Portfolio Report
```{r Portfolio Report, echo=F}
copy(STATISTIC.ACCOUNT.PL) %>%
  setnames(c('P/L', 'N', 'SUM', 'MEAN', 'MAX', 'SUM', 'MEAN', 'MAX', 'SUM', 'MEAN', 'MAX', 'MIN', 'N.MAX', 'N.MEAN', 'MAX', 'MEAN')) %>%
  extract(
    j = N := {
      win.percent <- N[c(TRUE, FALSE, FALSE)] / N[c(FALSE, FALSE, TRUE)] * 100
      char.n <- as.character(N)
      char.n[c(TRUE, FALSE, FALSE)] <- sprintf('%s (%.2f%%)', char.n[c(TRUE, FALSE, FALSE)], win.percent)
      char.n
    }
  ) %>%
  htmlTable(rnames = F,
            caption = 'PROFIT vs LOSS',
            css.table = "width: 100%; margin-top: 1em; margin-bottom: 1em;",
            css.cell = rep('width: 75px;', 16),
            cgroup = c('', '', 'MONEY', 'PIP', 'VOLUME', 'CONTINUOUS'),
            n.cgroup = c(1, 1, 3, 3, 4, 4),
            col.rgroup = c("none", "#F9FAF0"),
            col.columns = c("none", "#F1F0FA"))
  copy(STATISTIC.ACCOUNT.OTHERS) %>%
    extract(
      j = MDD.PERIOD := time.num.to.period.char(MDD.PERIOD)
    ) %>%
    htmlTable(rnames = F,
              caption = 'OTHERS',
              css.table = "width: 100%; margin-top: 1em; margin-bottom: 1em;",
              css.cell = rep('width: 64px;', 15),
              cgroup = c('PROF.YIELD.RETURN', 'EXIT', 'SUMMARY', 'MAX.DRAWDOWN'),
              n.cgroup = c(6, 4, 2, 3),
              col.rgroup = c("none", "#F9FAF0"),
              col.columns = c(rep("none", 6),
                              rep("#F1F0FA", 4),
                              rep("none", 2),
                              rep("#F1F0FA", 3))
              )

```

```{r Symbol Report, echo=F, fig.align='center', fig.width=10, message=FALSE, warning=FALSE}
symbols <- unique(TICKETS.EDITED[, SYMBOL])
n.symbols <- length(symbols)
if (n.symbols > 1) {
  tagList(
    tags$h2('Symbol Report'),
    copy(STATISTIC.SYMBOLS.PL) %>%
      extract(j = !c(1)) %>%
      setnames(c('P/L', 'N', 'SUM($)', 'MEAN($)', 'MAX($)', 'SUM', 'MEAN', 'MAX', 'SUM', 'MEAN', 'MAX', 'MIN', 'N.MAX', 'N.MEAN', 'MAX($)', 'MEAN($)')) %>%
      extract(
        j = N := {
        win.percent <- N[c(TRUE, FALSE, FALSE)] / N[c(FALSE, FALSE, TRUE)] * 100
        char.n <- as.character(N)
        char.n[c(TRUE, FALSE, FALSE)] <- sprintf('%s (%.2f%%)', char.n[c(TRUE, FALSE, FALSE)], win.percent)
        char.n
      }) %>%
      htmlTable(rnames = F,
                caption = 'PROFIT vs LOSS',
                css.table = "width: 100%; margin-top: 1em; margin-bottom: 1em;",
                css.cell = rep('width: 75px;', 16),
                rgroup = symbols,
                n.rgroup = rep(3, n.symbols),
                cgroup = c('', '', 'MONEY', 'PIP', 'VOLUME', 'CONTINUOUS'),
                n.cgroup = c(1, 1, 3, 3, 4, 4),
                col.rgroup = c("none", "#F9FAF0"),
                col.columns = c("none", "#F1F0FA")),
    copy(STATISTIC.SYMBOLS.OTHERS) %>%
      extract(j = !c(1)) %>%
      extract(
        j = MDD.PERIOD := time.num.to.period.char(MDD.PERIOD)
      ) %>%
      htmlTable(rnames = F,
                caption = 'OTHERS',
                css.table = "width: 100%; margin-top: 1em; margin-bottom: 1em;",
                rgroup = symbols,
                n.rgroup = rep(3, n.symbols),
                css.cell = rep('width: 64px;', 15),
                cgroup = c('PROF.YIELD.RETURN', 'EXIT', 'SUMMARY', 'MAX.DRAWDOWN'),
                n.cgroup = c(6, 4, 2, 3),
                col.rgroup = c("none", "#F9FAF0"),
                col.columns = c(rep("none", 6),
                                rep("#F1F0FA", 4),
                                rep("none", 2),
                                rep("#F1F0FA", 3))),
    SYMBOLS.RETURN %>%
      extract(j = !'TIME') %>%
      myAssetsCorImagePlot(abbreviate = 10)
  )
}
```

## Tickets Report
```{r Tickets Report, echo=F}
copy(TICKETS.EDITED) %>%
  setkey(OTIME) %>%
  extract(
    j = c('VOLUME', 'PERIOD', 'MFPP', 'MFLP') := list(round(VOLUME, 2), time.num.to.period.char(PERIOD), time.num.to.period.char(MFPP), time.num.to.period.char(MFLP))
  ) %>%
  extract(
    j = c('TICKET', 'ITEM', 'TYPE', 'VOLUME', 'OTIME', 'OPRICE', 'CTIME', 'CPRICE', 'SL', 'TP',
          'NPROFIT', 'PIP', 'MFP', 'MFPP', 'MFL', 'MFLP', 'PERIOD', 'EXIT'),
    with = FALSE
  ) %>%
  setnames(c('Ticket', 'Item', 'Type', 'Vol', 'Time', 'Price', 'Time', 'Price',' SL', 'TP',
             'NetProf', 'Pip', 'Prof', 'Prof.P', 'LOSS', 'Loss.P', 'Period', 'Exit')) %>%
  htmlTable(rnames = F,
            css.table = "width: 100%; margin-top: 1em; margin-bottom: 1em;",
            cgroup = c('', 'REQUEST', 'OPEN', 'CLOSE', 'STOPS', 'RESULT', 'MAX FLOATING', ''),
            n.cgroup = c(1, 3, 2, 2, 2, 2, 4, 2),
            col.rgroup = c("none", "#F9FAF0"),
            col.columns = c("none", "#F1F0FA"))
```

